---
- name: Memory usage monitoring
  hosts: localhost
  vars:
    - used: "{{ (ansible_memory_mb.real.used * 100) / ansible_memory_mb.real.total | int }}"
    - THRESHOLD: '50'

  tasks: 
    - name: Checking memory usage
      debug: 
        msg: Memory usage is above Threshold 
      when: used > THRESHOLD 
